# Generated by Django 4.1.3 on 2022-11-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contant", models.CharField(max_length=50)),
                ("post", models.TextField(max_length=50)),
            ],
        ),
    ]
